import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import contentRouter from "./content";
import publishingRouter from "./publishing";
import platformsRouter from "./platforms";
import platformGroupsRouter from "./platform-groups";
import publishingRulesRouter from "./publishing-rules";
import aiSettingsRouter from "./ai-settings";
import brandVoicesRouter from "./brand-voices";
import promptsRouter from "./prompts";
import styleReferencesRouter from "./style-references";
import specialtiesRouter from "./specialties";
import researchRouter from "./research";
import medicalVerificationRouter from "./medical-verification";
import trendsRouter from "./trends";
import competitorsRouter from "./competitors";
import alertsRouter from "./alerts";
import aiMemoryRouter from "./ai-memory";
import contentPillarsRouter from "./content-pillars";
import aiWorkflowsRouter from "./ai-workflows";
import knowledgeLibraryRouter from "./knowledge-library";
import campaignsRouter from "./campaigns";
import approvalsRouter from "./approvals";
import historyRouter from "./history";
import notificationsRouter from "./notifications";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(contentRouter);
router.use(publishingRouter);
router.use(platformsRouter);
router.use(platformGroupsRouter);
router.use(publishingRulesRouter);
router.use(aiSettingsRouter);
router.use(brandVoicesRouter);
router.use(promptsRouter);
router.use(styleReferencesRouter);
router.use(specialtiesRouter);
router.use(researchRouter);
router.use(medicalVerificationRouter);
router.use(trendsRouter);
router.use(competitorsRouter);
router.use(alertsRouter);
router.use(aiMemoryRouter);
router.use(contentPillarsRouter);
router.use(aiWorkflowsRouter);
router.use(knowledgeLibraryRouter);
router.use(campaignsRouter);
router.use(approvalsRouter);
router.use(historyRouter);
router.use(notificationsRouter);

export default router;
